### PR TITLE
[docs] 1.8.x: add troubleshooting item and fix annotation for ""_n operator

### LINKED ISSUE #955: [docs] Operator ""_n does not show in docs
File: [libraries/eosiolib/core/eosio/name.hpp](https://developers.eos.io/manuals/eosio.cdt/v1.7/name_8hpp)

Operator ""_n does not render in the v1.7 documentation - it does for [v1.5](https://developers.eos.io/manuals/eosio.cdt/v1.5/name_8hpp).

### PR DESCRIPTION
**Pull request by iamveritas**
- add troubleshooting item for error `system contract must first be initialized`
- fixes #955: the `@cond IMPLEMENTATIONS` was preventing doxygen from parsing the annotation for ""_n opearator
- a few cosmetic changes

sister PR: https://github.com/EOSIO/eosio.cdt/pull/1044

### CODE REVIEW

File: libraries/eosiolib/core/eosio/name.hpp [hunk 1]
```diff
@@ -313,11 +313,7 @@ namespace eosio {
    } /// namespace detail
 } /// namespace eosio
 
-/// @cond IMPLEMENTATIONS
```
Comment (iamveritas) [inline libraries/eosiolib/core/eosio/name.hpp:316]: @larryk85 I have to delete this annotation cause it is preventing doxygen from parsing the annotation for `_n()` operator and thus the operator is not documented in the reference documentation anymore

Comment (larryk85) [reply libraries/eosiolib/core/eosio/name.hpp:316]: Sure, that sounds fine.

File: docs/08_troubleshooting.md [hunk 2]
```diff
@@ -131,4 +149,16 @@ __Possible solution__: The key point here is the `expected order` and what you t
...
+The code above has one `print` statement before the `singleton_set.send` and another one after the `singleton_set.send`. If you wrote some more `print` statements in the code that implements the `singleton_set.send` action and expect to see them before the second `print` statement then it is a wrong assumption. The inline actions are broadcasted to the network and they are executed at a different time, asynchronous of the current execution thread of the current `multi_index_example::mod` action, therefor it is impossible to predict when the `print` statements from inline action code will be outputted.
+
+## Assertion failure while creating an account after eosio.system was installed
+
+```console
+cleos create account eosio bob EOS5HUanbay86UUnr1d4fuBsQ3ksjfgZYoLUVvrYVLy6pj4i8xqVY
+Error 3050003: eosio_assert_message assertion failure
+Error Details:
+assertion failure with message: system contract must first be initialized
+```
```
Comment (lparisc) [inline docs/08_troubleshooting.md:161]: Consider splitting the shell command and the output using \`\`\`sh and \`\`\`console, respectively.

**Review by lparisc — APPROVED** [review]

File: docs/08_troubleshooting.md (hunk 2 above)
Comment (iamveritas) [reply docs/08_troubleshooting.md:161]: yes, that is the goal in general, this was a slip, thanks!

**Review by lparisc — APPROVED** [review]
